version: 2
jobs:
  base:
    docker:
      - image: hongyuanjia/eplusr:9.1.0
    steps:
      - checkout
      - run: Rscript -e "stopifnot(eplusr::is_valid_eplus(9.1))"
  verse:
    docker:
      - image: hongyuanjia/eplusr:9.1.0-verse
    steps:
      - checkout
      - run: Rscript -e "stopifnot(eplusr::is_avail_eplus(9.1)); tinytex::r_texmf()"
