name: Build & Push images

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - 'master'

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup build arguments
        id: set-matrix
        run: |
          CONTENT=$(jq -r 'tostring' matrix.json)
          echo ::set-output name=matrix::${CONTENT}
          echo ${CONTENT}

  build:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    name: ${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ matrix.tag }}
          # build-time variables
          build-args: ${{ matrix.build_args }}}
          # Path to the Dockerfile
          file: ${{ matrix.file }}
          # Do not push on PR
          push: ${{ github.event_name != 'pull_request' }}
